import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const background = {
    backgroundImage: "url('https://s1.1zoom.me/b5441/516/England_Houses_Rivers_Bridges_Knaresborough_527029_1080x1920.jpg')",
  };
  return (
    <html lang="en">
      <body className="bg-fixed bg-cover" style={background}>
        {children}
      </body>
    </html>
  )
}
